Support 1.20.6
Slimefun/dough pull request #271
Opened 2024-05-29 21:37 UTC by EpicPlayerA10

### Changes
- Added required adapters for 1.20.6 due to internals breaking changes
- Added paper-specific adapters too. This change will make dough future-proof on paper.
- Added exclusions in `pom.xml` in module `dough-protection` because dough couldn't be compiled. This is because one of dependencies provided very old version of bukkit which broke compilation
- In main `pom.xml` changed from spigot to paper to be able to use paper features in adapters

2024-06-11 16:06 UTC, ybw0014 commented
ItemUtils.damageItem needs an update as well, the unbreaking enchantment enum name is renamed.

2024-06-13 08:17 UTC, DexterSK approved these changes

2024-06-13 11:40 UTC, ybw0014 commented
@DexterSK making noises cannot let this PR get merged faster

2024-06-15 17:33 UTC, EpicPlayerA10 commented
> ItemUtils.damageItem needs an update as well, the unbreaking enchantment enum name is renamed.

We don't need to do this as from what i see `dough` is not updating minecraft version in the pom.xml:
https://github.com/Slimefun/dough/blob/baf2d79f6209b928209721981df0487f17410ac1/pom.xml#L287-L292
And spigot already auto renames these fields for plugins that are built for older minecraft versions: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/legacy/FieldRename.java . So no error will be thrown.

2024-07-10 05:53 UTC, mcchampions commented
This pr conflicts with #219.

2024-08-08 22:38 UTC, IvanMishin1 approved these changes

2024-08-11 10:33 UTC, md5sha256 commented
> > ItemUtils.damageItem needs an update as well, the unbreaking enchantment enum name is renamed.
> 
> We don't need to do this as from what i see `dough` is not updating minecraft version in the pom.xml:
> 
> https://github.com/Slimefun/dough/blob/baf2d79f6209b928209721981df0487f17410ac1/pom.xml#L287-L292
> 
> 
> And spigot already auto renames these fields for plugins that are built for older minecraft versions: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/legacy/FieldRename.java . So no error will be thrown.

This does need to be updated as otherwise dough cannot compile if the consumer is compiling against 1.20.5+. The suggested fix is to refactor it to use the bukkit `Registry.ENCHANTMENT` api and grab it via the minecraft namespaced key.

2024-08-11 10:43 UTC, EpicPlayerA10 commented
Done

2024-08-12 09:04 UTC, mcchampions approved these changes

2024-08-12 09:07 UTC, mcchampions commented on dough-skins/src/main/java/io/github/bakedlibs/dough/skins/nms/PlayerHeadAdapterPaper.java
> +        paperPlayerProfile.setProperty(new ProfileProperty(property.name(), property.value(), property.signature()));
I should not operate on mobile web pages

2024-08-12 13:31 UTC, mcchampions requested changes

2024-08-12 13:31 UTC, mcchampions commented on dough-skins/src/main/java/io/github/bakedlibs/dough/skins/nms/PlayerHeadAdapterPaper.java
> +        paperPlayerProfile.setProperty(new ProfileProperty(property.name(), property.value(), property.signature()));
RecordJava started using records in Java 16, while Authlib didn't use records until much later. As of the last version of Paper 1.18.2 that depended on Authlib, Property was still a class. Therefore, you might need to use reflection to call the getter method of an older version of Property.

2024-09-08 23:00 UTC, ybw0014 requested changes
Based on the result server testing by boomer:

2024-09-08 23:00 UTC, ybw0014 requested changes

2024-09-08 23:00 UTC, ybw0014 commented on dough-items/src/main/java/io/github/bakedlibs/dough/items/nms/ItemNameAdapterPaper.java
Adventure isn't bundle in paper until 1.19.2/.4.

2024-09-09 03:13 UTC, WalshyDev approved these changes

2024-09-09 03:14 UTC, merged