Added ShopChest Protection Module
Slimefun/dough pull request #73
Opened 2021-08-24 17:14 UTC by EpicPlayerA10

## Description
Added ShopChest Protection Module

2021-08-24 18:26 UTC, md5sha256 requested changes

2021-08-24 18:26 UTC, md5sha256 commented on dough-protection/src/main/java/io/github/bakedlibs/dough/protection/modules/ShopChestProtectionModule.java
> +        }
If you only have two cases, it doesn't make sense to use a switch. Consider using an if else instead
```suggestion
    public boolean hasPermission(OfflinePlayer p, Location l, Interaction action) {
        if (action == Interaction.BREAK_BLOCK) {
                return !shopChest.getShopUtils().isShop(l);
        } else {
                return true;
        }
```

2021-09-13 11:00 UTC, md5sha256 commented
LGTM

2021-12-09 15:36 UTC, TheBusyBiscuit requested changes
Looks good implementation-wise.
We just need some documentation before I will merge this

2021-12-09 15:36 UTC, TheBusyBiscuit commented on dough-protection/src/main/java/io/github/bakedlibs/dough/protection/modules/ShopChestProtectionModule.java
> +public class ShopChestProtectionModule implements ProtectionModule {
Missing author tag and javadocs

2024-02-25 16:33 UTC, J3fftw1 approved these changes
LGTM

2024-02-25 16:33 UTC, J3fftw1 submitted a review, later dismissed
LGTM

2024-03-08 22:48 UTC, Sfiguz7 submitted a review, later dismissed

2024-03-08 22:53 UTC, Sfiguz7 approved these changes

2024-03-08 22:53 UTC, merged